server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|dxf)$ {
        add_header Cache-Control "no-store";
        types {
            text/javascript js mjs;
            text/css css;
            text/plain dxf;
        }
    }
}
